version: '3.8'

services:
  web:
    build: .
    ports:
      - "5004:5004"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/iot_platform
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - JWT_SECRET_BASE64=WsNiwFBf2CJqVRz8/9OT58zgsXtRqArsUtvoeFrI+rc=
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iot_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iot_platform"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data: 